### ISSUE TITLE
It doesn't work 

### ISSUE THREAD

**Issue by stpeterthe1** [robotlovesyou/AudioMixerDemo#1]
Can't make it run a few issue being fixed but then it just crashed right away

**Comment by robotlovesyou** [comment]
Hi, The code is quite old so that may well be the issue. What was the error message when it crashed (PS sorry about the slow reply!)

**Comment by robotlovesyou** [comment]
Closing this due to lack of response

**Comment by share9** [comment]
Here's the error:

2018-10-24 14:23:08.890130-0400 Audio Mixer Demo[90463:5783939] -[Audio_Mixer_Demo.ViewController playButtonTapped:]: unrecognized selector sent to instance 0x7fa6bfd09d20
2018-10-24 14:23:09.055072-0400 Audio Mixer Demo[90463:5783939] *** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '-[Audio_Mixer_Demo.ViewController playButtonTapped:]: unrecognized selector sent to instance 0x7fa6bfd09d20'
*** First throw call stack:
(
	0   CoreFoundation                      0x000000010277a29b __exceptionPreprocess + 331
	1   libobjc.A.dylib                     0x000000010189c735 objc_exception_throw + 48
	2   CoreFoundation                      0x0000000102798fa4 -[NSObject(NSObject) doesNotRecognizeSelector:] + 132
	3   UIKitCore                           0x000000010d10b163 -[UIResponder doesNotRecognizeSelector:] + 287
	4   CoreFoundation                      0x000000010277efb6 ___forwarding___ + 1446
	5   CoreFoundation                      0x0000000102780e88 _CF_forwarding_prep_0 + 120
	6   UIKitCore                           0x000000010cd257c3 -[UIApplication sendAction:to:from:forEvent:] + 83
	7   UIKitCore                           0x000000010ce5de85 -[UIControl sendAction:to:forEvent:] + 67
	8   UIKitCore                           0x000000010ce5e1a2 -[UIControl _sendActionsForEvents:withEvent:] + 450
	9   UIKitCore                           0x000000010ce5d0e6 -[UIControl touchesEnded:withEvent:] + 583
	10  UIKitCore                           0x000000010d538334 -[UIWindow _sendTouchesForEvent:] + 2729
	11  UIKitCore                           0x000000010d539a30 -[UIWindow sendEvent:] + 4080
	12  UIKitCore                           0x000000010cd3fe10 -[UIApplication sendEvent:] + 352
	13  UIKitCore                           0x000000010cc780d0 __dispatchPreprocessedEventFromEventQueue + 3024
	14  UIKitCore                           0x000000010cc7acf2 __handleEventQueueInternal + 5948
	15  CoreFoundation                      0x00000001026ddb31 __CFRUNLOOP_IS_CALLING_OUT_TO_A_SOURCE0_PERFORM_FUNCTION__ + 17
	16  CoreFoundation                      0x00000001026dd3a3 __CFRunLoopDoSources0 + 243
	17  CoreFoundation                      0x00000001026d7a4f __CFRunLoopRun + 1263
	18  CoreFoundation                      0x00000001026d7221 CFRunLoopRunSpecific + 625
	19  GraphicsServices                    0x00000001079cc1dd GSEventRunModal + 62
	20  UIKitCore                           0x000000010cd24115 UIApplicationMain + 140
	21  Audio Mixer Demo                    0x0000000100f70e74 main + 68
	22  libdyld.dylib                       0x0000000104c4f551 start + 1
	23  ???                                 0x0000000000000001 0x0 + 1
)
libc++abi.dylib: terminating with uncaught exception of type NSException
(lldb)
